### ISSUE TITLE
phalcon与cphalcon7的关系

### ISSUE THREAD

**Issue by afyji** [dreamsxin/cphalcon7#130]
之前我一直用的phalcon 2.9   现在也用到了3.1    请问cphalcon7与 原本的phalcon 3.1之间的关系是什么样的  代码貌似是比较兼容的

**Comment by dreamsxin** [comment]
Phalcon7 - 1.3 之后的分支，不使用 zephir。
Phalcon2 - 1.3 之后，使用 zephir 开发的版本。
