### ISSUE TITLE
i got an error when i make 

### ISSUE THREAD

**Issue by xiangbin001** [dreamsxin/cphalcon7#183]
php -v 
PHP 7.1.4 (cli) (built: Apr 14 2017 18:15:34) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

./configure --prefix=/usr/local/php7    --with-php-config=/usr/local/php7/bin/php-config --enable-storage-btree=yes
..............
.............
..............
creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
config.status: config.h is unchanged

make -j4
....
....
....
Downloads/php-extension/cphalcon7/ext/storage/btree/utils.c:29:10: error: expected ')'
uint64_t htonll(uint64_t value)
......
.....
....
Downloads/php-extension/cphalcon7/ext/storage/btree/utils.c:29:10: error: conflicting types for '__builtin_constant_p'
uint64_t htonll(uint64_t value)
....
....
....
Downloads/php-extension/cphalcon7/ext/storage/btree/utils.c:29:10: error: definition of builtin function '__builtin_constant_p'
uint64_t htonll(uint64_t value)
         ^
....
....
....
Downloads/php-extension/cphalcon7/ext/storage/btree/utils.c:41:10: error: expected ')'
uint64_t ntohll(uint64_t value)
.....
....
....
Downloads/php-extension/cphalcon7/ext/storage/btree/utils.c:41:10: error: conflicting types for '__builtin_constant_p'
uint64_t ntohll(uint64_t value)
....
...
..
Downloads/php-extension/cphalcon7/ext/storage/btree/utils.c:41:10: error: definition of builtin function '__builtin_constant_p'
uint64_t ntohll(uint64_t value)
.....
....
....
6 errors generated.
make: *** [storage/btree/utils.lo] Error 1

what can i do to fix these errors?

**Comment by dreamsxin** [comment]
您的系统是 OSX？我在分支 io 提交了一个 patch，你可以再测试下，`--enable-storage-btree=yes` 这个选项如果不是必须的，也可以暂时关闭它。

**Comment by xiangbin001** [comment]
是的，我的系统是OSX，我在您提交的io分支上重新编译后解决了这个问题，非常感谢！
