### ISSUE TITLE
在循环中，数据库切片、表切片工作错误

### ISSUE THREAD

**Issue by yxgong** [dreamsxin/cphalcon7#188]
表结构

`CREATE TABLE IF NOT EXISTS detail_0 (
	id int(11) unsigned NOT NULL AUTO_INCREMENT,
	uid bigint(20) unsigned NOT NULL DEFAULT '0',
	name varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	PRIMARY KEY (id),
	KEY uid (uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`

use \Phalcon\DI\FactoryDefault;
use \Phalcon\Logger;
use \Phalcon\Events\Manager as EventsManager;
use \Phalcon\Logger\Adapter\File as FileLogger;
use \Phalcon\Db\Adapter\Pdo\Mysql as Connection;
use \Phalcon\Mvc\Model as MvcModel;

define('IS_DEBUG', false);

class Detail extends MvcModel{
    public $id;
    public $uid;
    public $name;

	public function initialize()
	{
		$this->useDynamicUpdate(true);

		self::setup(array(
			'notNullValidations' => true,
			'virtualForeignKeys' => false,
			'strict' => true, //写库操作成功与否严格按照实际操作的条数，如果为0条就是false
			// 'astCache' => false,
		));

		$this->hashTbl(0);
		$this->setConnectionService('db0');
	}

	public function hashTbl($uid, $factor=3)
	{
		$this->setSource('detail_'.($uid%$factor));
	}

	public function hashConnection($uid, $factor=2)
	{
		$this->setConnectionService('db'.($uid%$factor));
	}

	public function append($uid, $params = array())
	{
		$this->hashTbl($uid, 3);
		//$this->hashConnection($uid, 2);
		self::save($params, ['id', 'uid', 'name']);
	
		return $this->id;
	}

}

$di = new FactoryDefault();

// database service start
$dbSettings = [
	"db0" => ['host' => '127.0.0.1', 'port' => 3306, 'username' => 'root', 'password' => 'devel.yangx', 'dbname' => 'tdb0', 'options' => [PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES 'utf8mb4'", PDO::ATTR_CASE => PDO::CASE_NATURAL]], 
	"db1" => ['host' => '127.0.0.1', 'port' => 3306, 'username' => 'root', 'password' => 'devel.yangx', 'dbname' => 'tdb1', 'options' => [PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES 'utf8mb4'", PDO::ATTR_CASE => PDO::CASE_NATURAL]]
];

foreach($dbSettings as $serviceName=>$dbSetting){
	$di->set($serviceName, function () use ($dbSetting) {
		$dbAdapterClass = '\Phalcon\Db\Adapter\Pdo\Mysql';
		$connection = new $dbAdapterClass($dbSetting);
		if (IS_DEBUG)
		{
			$eventsManager = new EventsManager();
			
			// Listen all the database events
			$eventsManager->attach('db', function ($event, $connection) {
				// var_dump($event->getType());
				if ($event->getType()=='beforeQuery'||$event->getType()=='beforeExecute')
				{
					echo "\n".date("r").$connection->getSQLStatement()."\n";
				}
			});
			
			$connection->setEventsManager($eventsManager);
		}
		
		return $connection;
	}, TRUE);
}
// database service end

// test database
$results = array(
	array('uid' => 77, 'name' => '我是第1条数据'),
	array('uid' => 78, 'name' => '我是第2条数据'),
	array('uid' => 79, 'name' => '我是第3条数据'),
	array('uid' => 80, 'name' => '我是第4条数据'),
	array('uid' => 81, 'name' => '我是第5条数据'),
	array('uid' => 82, 'name' => '我是第6条数据'),
);

foreach($results as $result)
{
	$mDetail = new Detail;
	$id = $mDetail->append($result['uid'], $result);
	var_dump($id);
}

**Comment by dreamsxin** [comment]
Fix in #189
