### ISSUE TITLE
朋友，你一个人维护这个，倒不如写个EasyPhalcon框架好些

### ISSUE THREAD

**Issue by nottellyou** [dreamsxin/cphalcon7#251]
朋友，你一个人维护这个，倒不如写个基于phalcon的PHP框架EasyPhalcon框架好些。　用户只需要在框架里添加controller和model，这样推广起来会相当的容易。

**Comment by dreamsxin** [comment]
谢谢您的建议，您说的这类，可以看看 
https://github.com/manaphp/phalma
http://phalconphp.org/
