### ISSUE TITLE
model中float类型保存不了

### ISSUE THREAD

**Issue by yangzhu6263736** [dreamsxin/cphalcon7#288]
类似
class User extends \Phalcon\Mvc\Model
{

    public $id;
    /**
     * @Column(type="string", length=11, nullable=false)
     */
    public $money1;
}
如果是
$user = new User();
$user->money1 = 1231.12
$user->save();
数据是正常的

但是 如果是从数据库中取出对像再设置 money1 浮点型就会变成整型
也就是说model中的数据insert 是可以的。。但 update有问题

我大概看了下
            print_r($connection->getSqlBindTypes());
insert money1的限制类型 是 2 update就变成了1.。

我目前使用的办法是
$user = User::getByUserId(123);
$user->money1 = 1231.12
$user->money1 += "";//相当于全部转换成字符串去保存
$user->save();
这样是可以的。

如果可以麻烦修复下吧。

**Comment by dreamsxin** [comment]
你是用注释设置字段类型的？数据库中实际类型是什么，是什么数据库，是否方便给个示例表结构。

**Comment by dreamsxin** [comment]
查找出来后打印$user->getDataTypes()看看。

**Comment by yangzhu6263736** [comment]
嗯。用注释设置了好像也没什么用。。数据库中字段类型用过varchar float 都不行。。

**Comment by dreamsxin** [comment]
今天测试了下，已经找到问题，修复了，等待合并。
