### ISSUE TITLE
Phalcon\ContinueException 与 initialize方法 兼容性问题

### ISSUE THREAD

**Issue by yxgong** [dreamsxin/cphalcon7#295]
Phalcon\ContinueException在控制器的initialize方法中调用后，没有设置 dispatcher->getLastHandler()

dispatcher->getLastHandler() 为空，个人猜想可能是没有设置 controller导致的。

请帮忙排查一下这个原因。

**Comment by yxgong** [comment]
问题描述不准确，详细描述一下。
controller的initialize方法中调用了 Phalcon\ContinueException 之后


在 

$application = new \Phalcon\Mvc\Application();
.............

$application->attachEvent( 'beforeSendResponse', function ($event, $response) use($di){

    $dispatcher = $di->get( 'dispatcher' );
    $controller = $dispatcher->getLastHandler();
    var_dump($controller);exit; // 这里$controller为空


});

**Comment by dreamsxin** [comment]
Fix in https://github.com/dreamsxin/cphalcon7/commit/b4cfbf06fd89eb7593fec67dfb029eb567df9792
