### ISSUE TITLE
编译时候报错如下 mac 10.13.6  PHP 7.1.20

### ISSUE THREAD

**Issue by AdwindOne** [dreamsxin/cphalcon7#384]
ld: 1813 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [phalcon.la] Error 1

**Comment by dreamsxin** [comment]
有更详细的信息么，是否是全新的编译。如果是更新后重新编译，可以先清理：
```shell
phpize --clean
./configure
make clean
make
```

**Comment by AdwindOne** [comment]
全新的编译，试过清理，在make 的时候 出现的
.......    cache/backend/.libs/mongo.o
duplicate symbol _original_zend_execute_internal in:
    .libs/phalcon.o
    cache/backend/.libs/mongo.o
duplicate symbol __zend_execute_internal in:
    .libs/phalcon.o
    cache/backend/.libs/mongo.o
duplicate symbol _original_zend_execute_ex in:
    .libs/phalcon.o
    mvc/model/metadata/.libs/mongo.o
duplicate symbol __zend_execute_ex in:
    .libs/phalcon.o
    mvc/model/metadata/.libs/mongo.o
duplicate symbol _original_zend_execute_internal in:
    .libs/phalcon.o
    mvc/model/metadata/.libs/mongo.o
duplicate symbol __zend_execute_internal in:
    .libs/phalcon.o
    mvc/model/metadata/.libs/mongo.o
duplicate symbol _original_zend_execute_ex in:
    .libs/phalcon.o
    assets/filters/.libs/jsminifier.o
duplicate symbol __zend_execute_ex in:
    .libs/phalcon.o
    assets/filters/.libs/jsminifier.o
duplicate symbol _original_zend_execute_internal in:
    .libs/phalcon.o
    assets/filters/.libs/jsminifier.o
duplicate symbol __zend_execute_internal in:
    .libs/phalcon.o
    assets/filters/.libs/jsminifier.o
duplicate symbol _original_zend_execute_ex in:
    .libs/phalcon.o
    assets/filters/.libs/cssminifier.o
duplicate symbol __zend_execute_ex in:
    .libs/phalcon.o
    assets/filters/.libs/cssminifier.o
duplicate symbol _original_zend_execute_internal in:
    .libs/phalcon.o
    assets/filters/.libs/cssminifier.o
duplicate symbol __zend_execute_internal in:
    .libs/phalcon.o
    assets/filters/.libs/cssminifier.o
ld: 1813 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [phalcon.la] Error 1

**Comment by Physton** [comment]
我跟你同样的问题，请问你解决了吗

**Comment by dreamsxin** [comment]
这个问题应该解决了，最新版仓库里的

**Comment by AdwindOne** [comment]
我今天又重新编译了一下，现在这个版本可以已经解决了 @Physton
