### ISSUE TITLE
macos编译安装报错

### ISSUE THREAD

**Issue by Physton** [dreamsxin/cphalcon7#400]
phpize，./configure的时候都没有问题。
make的时候报错：
    ld: 9 duplicate symbols for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [phalcon.la] Error 1
怎么都解决不了。
系统版本 macOS Mojave 10.14
xCode版本：10.1

**Comment by dreamsxin** [comment]
有更详细的错误么，确认是哪个头文件，我没有mac环境，所以没法测试。

**Comment by Physton** [comment]
> 有更详细的错误么，确认是哪个头文件，我没有mac环境，所以没法测试。

刚又重新clone了一下，编译还是出错，最后的错误具体信息：
/bin/sh /Users/physton/Downloads/cphalcon7/ext/libtool --mode=link cc -DPHP_ATOM_INC -I/Users/physton/Downloads/cphalcon7/ext/include -I/Users/physton/Downloads/cphalcon7/ext/main -I/Users/physton/Downloads/cphalcon7/ext -I/usr/local/Cellar/php@7.1/7.1.24/include/php -I/usr/local/Cellar/php@7.1/7.1.24/include/php/main -I/usr/local/Cellar/php@7.1/7.1.24/include/php/TSRM -I/usr/local/Cellar/php@7.1/7.1.24/include/php/Zend -I/usr/local/Cellar/php@7.1/7.1.24/include/php/ext -I/usr/local/Cellar/php@7.1/7.1.24/include/php/ext/date/lib -I/usr/local/include -I/usr/local/Cellar/imagemagick/7.0.8-14/include/ImageMagick-7  -I/usr/local/Cellar/libpng/1.6.35/include/libpng16 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick/7.0.8-14/include/ImageMagick-7 -DHAVE_CONFIG_H  -g -O2 -DPHALCON_RELEASE=1   -o phalcon.la -export-dynamic -avoid-version -prefer-pic -module -rpath /Users/physton/Downloads/cphalcon7/ext/modules -L/usr/local/Cellar/libpng/1.6.35/lib -lpng16 -lz -L/usr/local/Cellar/imagemagick/7.0.8-14/lib -lMagickWand-7.Q16HDRI -lMagickCore-7.Q16HDRI phalcon.lo kernel/main.lo kernel/fcall.lo kernel/require.lo kernel/debug.lo kernel/backtrace.lo kernel/object.lo kernel/array.lo kernel/hash.lo kernel/murmurhash.lo kernel/string.lo kernel/mbstring.lo kernel/filter.lo kernel/operators.lo kernel/concat.lo kernel/exception.lo kernel/file.lo kernel/output.lo kernel/memory.lo kernel/shm.lo kernel/mpool.lo kernel/avltree.lo kernel/rbtree.lo kernel/bloomfilter.lo kernel/countingbloomfilter.lo kernel/datrie/trie.lo kernel/datrie/alpha-map.lo kernel/datrie/darray.lo kernel/datrie/dstring.lo kernel/datrie/fileutils.lo kernel/datrie/tail.lo kernel/datrie/trie-string.lo kernel/list.lo kernel/session.lo kernel/variables.lo kernel/framework/orm.lo kernel/framework/router.lo kernel/framework/url.lo kernel/assert.lo kernel/exit.lo kernel/iterator.lo kernel/math.lo kernel/time.lo kernel/message/queue.lo kernel/io/support.lo kernel/io/epoll.lo kernel/io/kqueue.lo kernel/io/generic.lo kernel/io/sockets.lo kernel/io/networks.lo kernel/io/client.lo kernel/io/server.lo kernel/io/tasks.lo kernel/io/threads.lo kernel/gc.lo kernel/thread/pool.lo interned-strings.lo xhprof.lo logger.lo flash.lo security/exception.lo profiler.lo profilerinterface.lo profiler/item.lo profiler/iteminterface.lo profiler/exception.lo db/dialect/sqlite.lo db/dialect/mysql.lo db/dialect/postgresql.lo db/result/pdo.lo db/column.lo db/index.lo db/profiler/item.lo db/indexinterface.lo db/dialectinterface.lo db/resultinterface.lo db/profiler.lo db/referenceinterface.lo db/adapter/pdo/sqlite.lo db/adapter/pdo/mysql.lo db/adapter/pdo/postgresql.lo db/adapter/pdo.lo db/exception.lo db/reference.lo db/adapterinterface.lo db/dialect.lo db/adapter.lo db/rawvalue.lo db/columninterface.lo forms/form.lo forms/manager.lo forms/element/file.lo forms/element/email.lo forms/element/hidden.lo forms/element/password.lo forms/element/text.lo forms/element/select.lo forms/element/textarea.lo forms/element/check.lo forms/element/radio.lo forms/element/numeric.lo forms/element/submit.lo forms/element/date.lo forms/exception.lo forms/element.lo forms/elementinterface.lo http/parser/http_parser.lo http/parser.lo http/response.lo http/requestinterface.lo http/request.lo http/cookie.lo http/request/file.lo http/request/exception.lo http/request/fileinterface.lo http/responseinterface.lo http/cookie/exception.lo http/response/cookies.lo http/response/exception.lo http/response/headers.lo http/response/cookiesinterface.lo http/response/headersinterface.lo http/uri.lo http/client.lo http/client/exception.lo http/client/header.lo http/client/response.lo http/client/adapterinterface.lo http/client/adapter.lo http/client/adapter/curl.lo http/client/adapter/stream.lo dispatcherinterface.lo di.lo loader/exception.lo cryptinterface.lo db.lo text.lo arr.lo matrix.lo date.lo date/datetime.lo binary.lo binary/reader.lo binary/writer.lo binary/exception.lo debug.lo debug/exception.lo debug/dump.lo tag.lo user/component.lo user/plugin.lo user/module.lo user/logic.lo application.lo application/exception.lo router.lo routerinterface.lo router/exception.lo cli/dispatcher/exception.lo cli/console.lo cli/router.lo cli/task.lo cli/router/exception.lo cli/dispatcher.lo cli/console/exception.lo cli/options.lo cli/options/exception.lo cli/color.lo mvc/controller.lo mvc/dispatcher/exception.lo mvc/application/exception.lo mvc/router.lo mvc/micro.lo mvc/micro/middlewareinterface.lo mvc/micro/lazyloader.lo mvc/micro/exception.lo mvc/micro/collection.lo mvc/micro/collectioninterface.lo mvc/dispatcherinterface.lo mvc/routerinterface.lo mvc/urlinterface.lo mvc/user/component.lo mvc/user/plugin.lo mvc/user/module.lo mvc/user/logic.lo mvc/user/logic/model.lo mvc/url.lo mvc/model.lo mvc/view.lo mvc/modelinterface.lo mvc/router/group.lo mvc/router/route.lo mvc/router/annotations.lo mvc/router/exception.lo mvc/router/routeinterface.lo mvc/url/exception.lo mvc/viewinterface.lo mvc/dispatcher.lo mvc/view/engine/php.lo mvc/view/exception.lo mvc/view/engineinterface.lo mvc/view/simple.lo mvc/view/engine.lo mvc/view/model.lo mvc/view/modelinterface.lo mvc/application.lo mvc/controllerinterface.lo mvc/moduledefinitioninterface.lo mvc/model/metadata/files.lo mvc/model/metadata/strategy/introspection.lo mvc/model/metadata/strategy/annotations.lo mvc/model/metadata/apc.lo mvc/model/metadata/memory.lo mvc/model/metadata/session.lo mvc/model/metadata/memcached.lo mvc/model/metadata/redis.lo mvc/model/metadata/cache.lo mvc/model/transaction.lo mvc/model/metadata.lo mvc/model/resultsetinterface.lo mvc/model/managerinterface.lo mvc/model/behavior.lo mvc/model/query/exception.lo mvc/model/query/builder.lo mvc/model/query/builder/where.lo mvc/model/query/builder/join.lo mvc/model/query/builder/select.lo mvc/model/query/builder/update.lo mvc/model/query/builder/insert.lo mvc/model/query/builder/delete.lo mvc/model/query/lang.lo mvc/model/query/statusinterface.lo mvc/model/query/status.lo mvc/model/query/builderinterface.lo mvc/model/resultinterface.lo mvc/model/criteriainterface.lo mvc/model/query.lo mvc/model/resultset.lo mvc/model/validationfailed.lo mvc/model/manager.lo mvc/model/behaviorinterface.lo mvc/model/relation.lo mvc/model/exception.lo mvc/model/transaction/failed.lo mvc/model/transaction/managerinterface.lo mvc/model/transaction/manager.lo mvc/model/transaction/exception.lo mvc/model/queryinterface.lo mvc/model/row.lo mvc/model/criteria.lo mvc/model/resultset/complex.lo mvc/model/resultset/simple.lo mvc/model/behavior/timestampable.lo mvc/model/behavior/softdelete.lo mvc/model/metadatainterface.lo mvc/model/relationinterface.lo mvc/model/transactioninterface.lo config.lo config/adapter.lo config/adapterinterface.lo config/exception.lo config/adapter/ini.lo config/adapter/json.lo config/adapter/php.lo config/adapter/yaml.lo filterinterface.lo logger/multiple.lo logger/formatter/firephp.lo logger/formatter/json.lo logger/formatter/line.lo logger/formatter/syslog.lo logger/formatter.lo logger/adapter/file.lo logger/adapter/firephp.lo logger/adapter/stream.lo logger/adapter/syslog.lo logger/adapter/direct.lo logger/exception.lo logger/adapterinterface.lo logger/formatterinterface.lo logger/adapter.lo logger/item.lo filter/exception.lo filter/userfilterinterface.lo queue/beanstalk.lo queue/beanstalk/job.lo assets/resource/css.lo assets/resource/js.lo assets/filters/none.lo assets/filters/cssmin.lo assets/filters/jsmin.lo assets/filterinterface.lo assets/resource.lo assets/manager.lo assets/exception.lo assets/collection.lo escaper/exception.lo loader.lo tag/select.lo tag/exception.lo acl.lo acl/resource.lo acl/resourceaware.lo acl/resourceinterface.lo acl/adapter/memory.lo acl/exception.lo acl/role.lo acl/roleaware.lo acl/adapterinterface.lo acl/adapter.lo acl/roleinterface.lo exception.lo continueexception.lo exitexception.lo crypt.lo filter.lo dispatcher.lo cache/multiple.lo cache/frontend/none.lo cache/frontend/base64.lo cache/frontend/json.lo cache/frontend/igbinary.lo cache/frontend/data.lo cache/frontend/output.lo cache/backend/file.lo cache/backend/apc.lo cache/backend/memcached.lo cache/backend/memory.lo cache/backend/redis.lo cache/backend/yac.lo cache/exception.lo cache/backendinterface.lo cache/frontendinterface.lo cache/backend.lo session/bag.lo session/adapter/files.lo session/exception.lo session/baginterface.lo session/adapterinterface.lo session/adapter.lo session/adapter/memcached.lo session/adapter/cache.lo diinterface.lo escaper.lo crypt/exception.lo events/managerinterface.lo events/manager.lo events/eventinterface.lo events/event.lo events/exception.lo events/eventsawareinterface.lo events/listener.lo escaperinterface.lo validationinterface.lo validation.lo version.lo flashinterface.lo kernel.lo paginator/adapter.lo paginator/adapter/model.lo paginator/adapter/nativearray.lo paginator/adapter/querybuilder.lo paginator/adapter/sql.lo paginator/exception.lo paginator/adapterinterface.lo di/injectable.lo di/factorydefault.lo di/service/builder.lo di/serviceinterface.lo di/factorydefault/cli.lo di/exception.lo di/injectionawareinterface.lo di/service.lo random.lo security.lo security/random.lo annotations/reflection.lo annotations/annotation.lo annotations/readerinterface.lo annotations/adapter/files.lo annotations/adapter/apc.lo annotations/adapter/memory.lo annotations/adapter/cache.lo annotations/exception.lo annotations/collection.lo annotations/adapterinterface.lo annotations/adapter.lo annotations/reader.lo flash/direct.lo flash/exception.lo flash/session.lo translate/adapter/nativearray.lo translate/exception.lo translate/adapterinterface.lo translate/adapter.lo translate/adapter/gettext.lo translate/adapter/php.lo validation/validatorinterface.lo validation/message/group.lo validation/exception.lo validation/message.lo validation/messageinterface.lo validation/validator/email.lo validation/validator/presenceof.lo validation/validator/confirmation.lo validation/validator/regex.lo validation/validator/exclusionin.lo validation/validator/identical.lo validation/validator/between.lo validation/validator/inclusionin.lo validation/validator/stringlength.lo validation/validator/url.lo validation/validator/file.lo validation/validator/numericality.lo validation/validator/json.lo validation/validator/uniqueness.lo validation/validator/alnum.lo validation/validator/alpha.lo validation/validator/digit.lo validation/validator/date.lo validation/validator.lo mvc/model/query/parser.lo mvc/model/query/scanner.lo annotations/parser.lo annotations/scanner.lo image.lo image/adapter.lo image/adapterinterface.lo image/exception.lo image/adapter/gd.lo image/adapter/imagick.lo registry.lo async.lo thread/exception.lo thread/pool.lo chart/exception.lo chart/captcha/tiny.lo socket/exception.lo socket.lo socket/client.lo socket/server.lo process/exception.lo storage/exception.lo snowflake.lo server/utils.lo server/simple.lo server/exception.lo aop/lexer.lo aop/exception.lo aop/joinpoint.lo aop.lo assets/filters/jsminifier.lo assets/filters/cssminifier.lo
cc ${wl}-flat_namespace ${wl}-undefined ${wl}suppress -o .libs/phalcon.so -bundle  .libs/phalcon.o kernel/.libs/main.o kernel/.libs/fcall.o kernel/.libs/require.o kernel/.libs/debug.o kernel/.libs/backtrace.o kernel/.libs/object.o kernel/.libs/array.o kernel/.libs/hash.o kernel/.libs/murmurhash.o kernel/.libs/string.o kernel/.libs/mbstring.o kernel/.libs/filter.o kernel/.libs/operators.o kernel/.libs/concat.o kernel/.libs/exception.o kernel/.libs/file.o kernel/.libs/output.o kernel/.libs/memory.o kernel/.libs/shm.o kernel/.libs/mpool.o kernel/.libs/avltree.o kernel/.libs/rbtree.o kernel/.libs/bloomfilter.o kernel/.libs/countingbloomfilter.o kernel/datrie/.libs/trie.o kernel/datrie/.libs/alpha-map.o kernel/datrie/.libs/darray.o kernel/datrie/.libs/dstring.o kernel/datrie/.libs/fileutils.o kernel/datrie/.libs/tail.o kernel/datrie/.libs/trie-string.o kernel/.libs/list.o kernel/.libs/session.o kernel/.libs/variables.o kernel/framework/.libs/orm.o kernel/framework/.libs/router.o kernel/framework/.libs/url.o kernel/.libs/assert.o kernel/.libs/exit.o kernel/.libs/iterator.o kernel/.libs/math.o kernel/.libs/time.o kernel/message/.libs/queue.o kernel/io/.libs/support.o kernel/io/.libs/epoll.o kernel/io/.libs/kqueue.o kernel/io/.libs/generic.o kernel/io/.libs/sockets.o kernel/io/.libs/networks.o kernel/io/.libs/client.o kernel/io/.libs/server.o kernel/io/.libs/tasks.o kernel/io/.libs/threads.o kernel/.libs/gc.o kernel/thread/.libs/pool.o .libs/interned-strings.o .libs/xhprof.o .libs/logger.o .libs/flash.o security/.libs/exception.o .libs/profiler.o .libs/profilerinterface.o profiler/.libs/item.o profiler/.libs/iteminterface.o profiler/.libs/exception.o db/dialect/.libs/sqlite.o db/dialect/.libs/mysql.o db/dialect/.libs/postgresql.o db/result/.libs/pdo.o db/.libs/column.o db/.libs/index.o db/profiler/.libs/item.o db/.libs/indexinterface.o db/.libs/dialectinterface.o db/.libs/resultinterface.o db/.libs/profiler.o db/.libs/referenceinterface.o db/adapter/pdo/.libs/sqlite.o db/adapter/pdo/.libs/mysql.o db/adapter/pdo/.libs/postgresql.o db/adapter/.libs/pdo.o db/.libs/exception.o db/.libs/reference.o db/.libs/adapterinterface.o db/.libs/dialect.o db/.libs/adapter.o db/.libs/rawvalue.o db/.libs/columninterface.o forms/.libs/form.o forms/.libs/manager.o forms/element/.libs/file.o forms/element/.libs/email.o forms/element/.libs/hidden.o forms/element/.libs/password.o forms/element/.libs/text.o forms/element/.libs/select.o forms/element/.libs/textarea.o forms/element/.libs/check.o forms/element/.libs/radio.o forms/element/.libs/numeric.o forms/element/.libs/submit.o forms/element/.libs/date.o forms/.libs/exception.o forms/.libs/element.o forms/.libs/elementinterface.o http/parser/.libs/http_parser.o http/.libs/parser.o http/.libs/response.o http/.libs/requestinterface.o http/.libs/request.o http/.libs/cookie.o http/request/.libs/file.o http/request/.libs/exception.o http/request/.libs/fileinterface.o http/.libs/responseinterface.o http/cookie/.libs/exception.o http/response/.libs/cookies.o http/response/.libs/exception.o http/response/.libs/headers.o http/response/.libs/cookiesinterface.o http/response/.libs/headersinterface.o http/.libs/uri.o http/.libs/client.o http/client/.libs/exception.o http/client/.libs/header.o http/client/.libs/response.o http/client/.libs/adapterinterface.o http/client/.libs/adapter.o http/client/adapter/.libs/curl.o http/client/adapter/.libs/stream.o .libs/dispatcherinterface.o .libs/di.o loader/.libs/exception.o .libs/cryptinterface.o .libs/db.o .libs/text.o .libs/arr.o .libs/matrix.o .libs/date.o date/.libs/datetime.o .libs/binary.o binary/.libs/reader.o binary/.libs/writer.o binary/.libs/exception.o .libs/debug.o debug/.libs/exception.o debug/.libs/dump.o .libs/tag.o user/.libs/component.o user/.libs/plugin.o user/.libs/module.o user/.libs/logic.o .libs/application.o application/.libs/exception.o .libs/router.o .libs/routerinterface.o router/.libs/exception.o cli/dispatcher/.libs/exception.o cli/.libs/console.o cli/.libs/router.o cli/.libs/task.o cli/router/.libs/exception.o cli/.libs/dispatcher.o cli/console/.libs/exception.o cli/.libs/options.o cli/options/.libs/exception.o cli/.libs/color.o mvc/.libs/controller.o mvc/dispatcher/.libs/exception.o mvc/application/.libs/exception.o mvc/.libs/router.o mvc/.libs/micro.o mvc/micro/.libs/middlewareinterface.o mvc/micro/.libs/lazyloader.o mvc/micro/.libs/exception.o mvc/micro/.libs/collection.o mvc/micro/.libs/collectioninterface.o mvc/.libs/dispatcherinterface.o mvc/.libs/routerinterface.o mvc/.libs/urlinterface.o mvc/user/.libs/component.o mvc/user/.libs/plugin.o mvc/user/.libs/module.o mvc/user/.libs/logic.o mvc/user/logic/.libs/model.o mvc/.libs/url.o mvc/.libs/model.o mvc/.libs/view.o mvc/.libs/modelinterface.o mvc/router/.libs/group.o mvc/router/.libs/route.o mvc/router/.libs/annotations.o mvc/router/.libs/exception.o mvc/router/.libs/routeinterface.o mvc/url/.libs/exception.o mvc/.libs/viewinterface.o mvc/.libs/dispatcher.o mvc/view/engine/.libs/php.o mvc/view/.libs/exception.o mvc/view/.libs/engineinterface.o mvc/view/.libs/simple.o mvc/view/.libs/engine.o mvc/view/.libs/model.o mvc/view/.libs/modelinterface.o mvc/.libs/application.o mvc/.libs/controllerinterface.o mvc/.libs/moduledefinitioninterface.o mvc/model/metadata/.libs/files.o mvc/model/metadata/strategy/.libs/introspection.o mvc/model/metadata/strategy/.libs/annotations.o mvc/model/metadata/.libs/apc.o mvc/model/metadata/.libs/memory.o mvc/model/metadata/.libs/session.o mvc/model/metadata/.libs/memcached.o mvc/model/metadata/.libs/redis.o mvc/model/metadata/.libs/cache.o mvc/model/.libs/transaction.o mvc/model/.libs/metadata.o mvc/model/.libs/resultsetinterface.o mvc/model/.libs/managerinterface.o mvc/model/.libs/behavior.o mvc/model/query/.libs/exception.o mvc/model/query/.libs/builder.o mvc/model/query/builder/.libs/where.o mvc/model/query/builder/.libs/join.o mvc/model/query/builder/.libs/select.o mvc/model/query/builder/.libs/update.o mvc/model/query/builder/.libs/insert.o mvc/model/query/builder/.libs/delete.o mvc/model/query/.libs/lang.o mvc/model/query/.libs/statusinterface.o mvc/model/query/.libs/status.o mvc/model/query/.libs/builderinterface.o mvc/model/.libs/resultinterface.o mvc/model/.libs/criteriainterface.o mvc/model/.libs/query.o mvc/model/.libs/resultset.o mvc/model/.libs/validationfailed.o mvc/model/.libs/manager.o mvc/model/.libs/behaviorinterface.o mvc/model/.libs/relation.o mvc/model/.libs/exception.o mvc/model/transaction/.libs/failed.o mvc/model/transaction/.libs/managerinterface.o mvc/model/transaction/.libs/manager.o mvc/model/transaction/.libs/exception.o mvc/model/.libs/queryinterface.o mvc/model/.libs/row.o mvc/model/.libs/criteria.o mvc/model/resultset/.libs/complex.o mvc/model/resultset/.libs/simple.o mvc/model/behavior/.libs/timestampable.o mvc/model/behavior/.libs/softdelete.o mvc/model/.libs/metadatainterface.o mvc/model/.libs/relationinterface.o mvc/model/.libs/transactioninterface.o .libs/config.o config/.libs/adapter.o config/.libs/adapterinterface.o config/.libs/exception.o config/adapter/.libs/ini.o config/adapter/.libs/json.o config/adapter/.libs/php.o config/adapter/.libs/yaml.o .libs/filterinterface.o logger/.libs/multiple.o logger/formatter/.libs/firephp.o logger/formatter/.libs/json.o logger/formatter/.libs/line.o logger/formatter/.libs/syslog.o logger/.libs/formatter.o logger/adapter/.libs/file.o logger/adapter/.libs/firephp.o logger/adapter/.libs/stream.o logger/adapter/.libs/syslog.o logger/adapter/.libs/direct.o logger/.libs/exception.o logger/.libs/adapterinterface.o logger/.libs/formatterinterface.o logger/.libs/adapter.o logger/.libs/item.o filter/.libs/exception.o filter/.libs/userfilterinterface.o queue/.libs/beanstalk.o queue/beanstalk/.libs/job.o assets/resource/.libs/css.o assets/resource/.libs/js.o assets/filters/.libs/none.o assets/filters/.libs/cssmin.o assets/filters/.libs/jsmin.o assets/.libs/filterinterface.o assets/.libs/resource.o assets/.libs/manager.o assets/.libs/exception.o assets/.libs/collection.o escaper/.libs/exception.o .libs/loader.o tag/.libs/select.o tag/.libs/exception.o .libs/acl.o acl/.libs/resource.o acl/.libs/resourceaware.o acl/.libs/resourceinterface.o acl/adapter/.libs/memory.o acl/.libs/exception.o acl/.libs/role.o acl/.libs/roleaware.o acl/.libs/adapterinterface.o acl/.libs/adapter.o acl/.libs/roleinterface.o .libs/exception.o .libs/continueexception.o .libs/exitexception.o .libs/crypt.o .libs/filter.o .libs/dispatcher.o cache/.libs/multiple.o cache/frontend/.libs/none.o cache/frontend/.libs/base64.o cache/frontend/.libs/json.o cache/frontend/.libs/igbinary.o cache/frontend/.libs/data.o cache/frontend/.libs/output.o cache/backend/.libs/file.o cache/backend/.libs/apc.o cache/backend/.libs/memcached.o cache/backend/.libs/memory.o cache/backend/.libs/redis.o cache/backend/.libs/yac.o cache/.libs/exception.o cache/.libs/backendinterface.o cache/.libs/frontendinterface.o cache/.libs/backend.o session/.libs/bag.o session/adapter/.libs/files.o session/.libs/exception.o session/.libs/baginterface.o session/.libs/adapterinterface.o session/.libs/adapter.o session/adapter/.libs/memcached.o session/adapter/.libs/cache.o .libs/diinterface.o .libs/escaper.o crypt/.libs/exception.o events/.libs/managerinterface.o events/.libs/manager.o events/.libs/eventinterface.o events/.libs/event.o events/.libs/exception.o events/.libs/eventsawareinterface.o events/.libs/listener.o .libs/escaperinterface.o .libs/validationinterface.o .libs/validation.o .libs/version.o .libs/flashinterface.o .libs/kernel.o paginator/.libs/adapter.o paginator/adapter/.libs/model.o paginator/adapter/.libs/nativearray.o paginator/adapter/.libs/querybuilder.o paginator/adapter/.libs/sql.o paginator/.libs/exception.o paginator/.libs/adapterinterface.o di/.libs/injectable.o di/.libs/factorydefault.o di/service/.libs/builder.o di/.libs/serviceinterface.o di/factorydefault/.libs/cli.o di/.libs/exception.o di/.libs/injectionawareinterface.o di/.libs/service.o .libs/random.o .libs/security.o security/.libs/random.o annotations/.libs/reflection.o annotations/.libs/annotation.o annotations/.libs/readerinterface.o annotations/adapter/.libs/files.o annotations/adapter/.libs/apc.o annotations/adapter/.libs/memory.o annotations/adapter/.libs/cache.o annotations/.libs/exception.o annotations/.libs/collection.o annotations/.libs/adapterinterface.o annotations/.libs/adapter.o annotations/.libs/reader.o flash/.libs/direct.o flash/.libs/exception.o flash/.libs/session.o translate/adapter/.libs/nativearray.o translate/.libs/exception.o translate/.libs/adapterinterface.o translate/.libs/adapter.o translate/adapter/.libs/gettext.o translate/adapter/.libs/php.o validation/.libs/validatorinterface.o validation/message/.libs/group.o validation/.libs/exception.o validation/.libs/message.o validation/.libs/messageinterface.o validation/validator/.libs/email.o validation/validator/.libs/presenceof.o validation/validator/.libs/confirmation.o validation/validator/.libs/regex.o validation/validator/.libs/exclusionin.o validation/validator/.libs/identical.o validation/validator/.libs/between.o validation/validator/.libs/inclusionin.o validation/validator/.libs/stringlength.o validation/validator/.libs/url.o validation/validator/.libs/file.o validation/validator/.libs/numericality.o validation/validator/.libs/json.o validation/validator/.libs/uniqueness.o validation/validator/.libs/alnum.o validation/validator/.libs/alpha.o validation/validator/.libs/digit.o validation/validator/.libs/date.o validation/.libs/validator.o mvc/model/query/.libs/parser.o mvc/model/query/.libs/scanner.o annotations/.libs/parser.o annotations/.libs/scanner.o .libs/image.o image/.libs/adapter.o image/.libs/adapterinterface.o image/.libs/exception.o image/adapter/.libs/gd.o image/adapter/.libs/imagick.o .libs/registry.o .libs/async.o thread/.libs/exception.o thread/.libs/pool.o chart/.libs/exception.o chart/captcha/.libs/tiny.o socket/.libs/exception.o .libs/socket.o socket/.libs/client.o socket/.libs/server.o process/.libs/exception.o storage/.libs/exception.o .libs/snowflake.o server/.libs/utils.o server/.libs/simple.o server/.libs/exception.o aop/.libs/lexer.o aop/.libs/exception.o aop/.libs/joinpoint.o .libs/aop.o assets/filters/.libs/jsminifier.o assets/filters/.libs/cssminifier.o  -L/usr/local/Cellar/libpng/1.6.35/lib -lpng16 -lz -L/usr/local/Cellar/imagemagick/7.0.8-14/lib /usr/local/Cellar/imagemagick/7.0.8-14/lib/libMagickWand-7.Q16HDRI.dylib -L/usr/local/Cellar/little-cms2/2.9/lib -L/usr/local/opt/freetype/lib -L/usr/local/Cellar/xz/5.2.4/lib /usr/local/Cellar/imagemagick/7.0.8-14/lib/libMagickCore-7.Q16HDRI.dylib
duplicate symbol _original_zend_std_write_property in:
    .libs/phalcon.o
    aop/.libs/lexer.o
duplicate symbol _original_zend_std_read_property in:
    .libs/phalcon.o
    aop/.libs/lexer.o
duplicate symbol _original_zend_std_get_property_ptr_ptr in:
    .libs/phalcon.o
    aop/.libs/lexer.o
duplicate symbol _original_zend_std_write_property in:
    .libs/phalcon.o
    aop/.libs/joinpoint.o
duplicate symbol _original_zend_std_read_property in:
    .libs/phalcon.o
    aop/.libs/joinpoint.o
duplicate symbol _original_zend_std_get_property_ptr_ptr in:
    .libs/phalcon.o
    aop/.libs/joinpoint.o
duplicate symbol _original_zend_std_write_property in:
    .libs/phalcon.o
    .libs/aop.o
duplicate symbol _original_zend_std_read_property in:
    .libs/phalcon.o
    .libs/aop.o
duplicate symbol _original_zend_std_get_property_ptr_ptr in:
    .libs/phalcon.o
    .libs/aop.o
ld: 9 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [phalcon.la] Error 1
[Log at 2018-11-14 22-59-08.txt](https://github.com/dreamsxin/cphalcon7/files/2581220/Log.at.2018-11-14.22-59-08.txt)

**Comment by dreamsxin** [comment]
你可以试试这个kernel分支，修改了下。

**Comment by Physton** [comment]
> 你可以试试这个kernel分支，修改了下。

万分感谢，成功编译了
