### ISSUE TITLE
phalcon会话的问题。

### ISSUE THREAD

**Issue by 857475481** [dreamsxin/cphalcon7#450]
为什么在DI中注册session以后,比如：
$di->set('session',function(){
$session=new Phalcon\Session\Adapter\Files();
$session->start();
return $session;
});
在控制器中:
public function index()
{
$this->session->set('demo','set a variable!!');
这一句话提示Files这个类没有start的方法存在。
}
一直找不到问题的所在！！help me！！！

**Comment by dreamsxin** [comment]
复制上的完整错误输出

**Comment by dreamsxin** [comment]
Phalcon 4使用方法如下：
```php
$session=new Phalcon\Session\Manage();
$session->setHandler(new Phalcon\Session\Adapter\Files())
$session->start();
```
