### ISSUE TITLE
phalcon7图像处理相关bug

### ISSUE THREAD

**Issue by daixunxing** [dreamsxin/cphalcon7#455]
cphalcon7/ext/image/adapter/imagick.c
类中_watermark方法有bug
phalcon_get_intval(opacity) < 100调整透明度，调用的evaluateImage方法，此方法的透明度并不是1以下，为2是50%，所以永远调不了透明度
还有line方法调用无效。

**Comment by dreamsxin** [comment]
是因为类型没有转换的原因 `num = (double)Z_LVAL_P(opacity) / 100;`
