### ISSUE TITLE
图像处理类的问题

### ISSUE THREAD

**Issue by daixunxing** [dreamsxin/cphalcon7#456]
PHP_METHOD(Phalcon_Image_Adapter_Imagick, line){方法中的
if (Z_TYPE(image) == IS_RESOURCE) { 此处判断是否有问题？Z_TYPE得到的值为7，常量类型，IS_RESOURCE是8，调试图片就一个正常路径的png图片

**Comment by dreamsxin** [comment]
应该是 IS_OBJECT

**Comment by dreamsxin** [comment]
改好了
