### ISSUE TITLE
make: warning:  Clock skew detected.  Your build may be incomplete.

### ISSUE THREAD

**Issue by DoATrulyPhper** [dreamsxin/cphalcon7#487]
I encountered a problem
in install cphalcon7  appear  ‘make: warning:  Clock skew detected.  Your build may be incomplete.‘

env.config
php7.2.2
centos7.0
gcc4.8.5

**Comment by dreamsxin** [comment]
View system date
```shell
date
```

**Comment by DoATrulyPhper** [comment]
系统时间和当前时间不一致，需要调整一下重新安装吗？

**Comment by Aha233Unravel** [comment]
php扩展装不上，在make的时候报了 warning: Clock skew detected. Your build may be incomplete. 或者有别的原因吗，步骤重装好几遍了

**Comment by dreamsxin** [comment]
把系统系统调整到当前时间，大于源码文件的修改时间

**Comment by Aha233Unravel** [comment]
不报错了，但是php扩展还是没有，重启了已经

**Comment by dreamsxin** [comment]
fpm，编写 test.php 
```php
<?php
phpinfo();
``` 浏览器中打开 http://localhost/test.php，看加载的配置文件列表，是否有你添加 extension=phalcon.so 的文件。

cli，执行`php --ini`，看加载的配置文件列表，是否有你添加 extension=phalcon.so 的文件。

**Comment by Aha233Unravel** [comment]
/usr/local/php/lib/php/extensions/no-debug-non-zts-20170718/已经有phalcon.so，php.ini中也加了extension=phalcon.so，phpinfo()还是读不到扩展

**Comment by dreamsxin** [comment]
如果没有错误，就是加的位置有问题，按照我上面的方式检查，一般都能发现。
cli 下 `php -m` 如果加载失败会直接输出错误信息。
fpm，模式，应该也会在log中输出错误。

**Comment by dreamsxin** [comment]
`phpinfo` 会输出加载了哪些配置文件，fpm和cli默认一般使用不同的配置文件。

**Comment by Aha233Unravel** [comment]
All right, thanks

**Comment by DoATrulyPhper** [comment]
@dreamsxin 3Q
