### ISSUE TITLE
mac环境make报错

### ISSUE THREAD

**Issue by pygroos** [dreamsxin/cphalcon7#505]
macos: 10.15.7
php: 7.4.12
执行make -j4报如下错误

/Users/pygroos/Downloads/cphalcon7-kernel/ext/kernel/require.c:119:50: error: too many arguments to function call, expected 4,
      have 5
                        (zend_function*)op_array, 0, op_array->scope, object ? Z_OBJ_P(object) : NULL);
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/php/7.4.12/include/php/Zend/zend_execute.h:219:1: note: 'zend_vm_stack_push_call_frame' declared here
static zend_always_inline zend_execute_data *zend_vm_stack_push_call_frame(uint32_t call_info, zend_function *func, uint32...
^
1 warning and 1 error generated.
make: *** [kernel/require.lo] Error 1
make: *** Waiting for unfinished jobs....
1 warning generated.
In file included from /Users/pygroos/Downloads/cphalcon7-kernel/ext/phalcon.c:41:
In file included from ./phalcon.h:386:
./arr.h:59:3: error: unknown type name 'ulong'
  ulong num_alias;
  ^
./arr.h:60:3: error: unknown type name 'ulong'
  ulong num_selector;
  ^
/Users/pygroos/Downloads/cphalcon7-kernel/ext/phalcon.c:155:28: warning: incompatible pointer types assigning to
      'zend_object_write_property_t' (aka 'struct _zval_struct *(*)(struct _zval_struct *, struct _zval_struct *, struct
      _zval_struct *, void **)') from 'void (zval *, zval *, zval *, void **)' (aka 'void (struct _zval_struct *, struct
      _zval_struct *, struct _zval_struct *, void **)') [-Wincompatible-pointer-types]
                handlers->write_property = phalcon_aop_write_property;
                                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings and 2 errors generated.
1 warning generated.
make: *** [phalcon.lo] Error 1

**Comment by dreamsxin** [comment]
Phalcon7 代码是最新的么，看错误，感觉是 `php-config` 版本没对上。
我本地环境：
OS: Linux
PHP: 7.4.12
