### ISSUE TITLE
从model::findFirst取出数据toArray后通过redis->hMSet存储导致php崩溃

### ISSUE THREAD

**Issue by yxgong** [dreamsxin/cphalcon7#511]
环境： CentOS7.6x64 + PHP7.3.27 + Redis5.3.3

通过 Model的findFirst取出的数据，用 toArray转化为数组，然后向redis内通过hMSet方法存储hash结构，结果导致PHP崩溃。

通过gdb调试发现报错内容如下：

`

(gdb) bt
#0  0x00007ffff4a48387 in raise () from /usr/lib64/libc.so.6
#1  0x00007ffff4a49a78 in abort () from /usr/lib64/libc.so.6
#2  0x00007ffff4a411a6 in __assert_fail_base () from /usr/lib64/libc.so.6
#3  0x00007ffff4a41252 in __assert_fail () from /usr/lib64/libc.so.6
#4  0x0000000000aca9bd in zval_get_string_func (op=0x7ffff0791600)
    at /opt/distfiles/php/php-7.3.27/Zend/zend_operators.c:898
#5  0x00007fffe6df3c38 in zval_get_string (op=0x7ffff0791600)
    at /opt/php7/include/php/Zend/zend_operators.h:272
#6  0x00007fffe6dfb7f6 in redis_serialize (redis_sock=0x7ffff067a380, z=0x7ffff0791600, 
    val=0x7fffffff8bf0, val_len=0x7fffffff8be8)
    at /opt/distfiles/php/redis-5.3.3/library.c:2971
#7  0x00007fffe6dfb63e in redis_pack (redis_sock=0x7ffff067a380, z=0x7ffff0791600, 
    val=0x7fffffff8c78, val_len=0x7fffffff8c70)
    at /opt/distfiles/php/redis-5.3.3/library.c:2726
#8  0x00007fffe6dec524 in redis_hmset_cmd (execute_data=0x7ffff06223c0, 
    return_value=0x7ffff06223b0, redis_sock=0x7ffff067a380, cmd=0x7fffffff8d50, 
    cmd_len=0x7fffffff8d4c, slot=0x0, ctx=0x7fffffff8d40)
    at /opt/distfiles/php/redis-5.3.3/redis_commands.c:1719
#9  0x00007fffe6dd738d in zim_Redis_hMset (execute_data=0x7ffff06223c0, 
    return_value=0x7ffff06223b0) at /opt/distfiles/php/redis-5.3.3/redis.c:2431
#10 0x0000000000b3d923 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER ()
    at /opt/distfiles/php/php-7.3.27/Zend/zend_vm_execute.h:1106
#11 0x0000000000ba4b4b in execute_ex (ex=0x7ffff06221a0)
    at /opt/distfiles/php/php-7.3.27/Zend/zend_vm_execute.h:55527
#12 0x0000000000ac1671 in zend_call_function (fci=0x7fffffff9120, fci_cache=0x7fffffff8fd0)
    at /opt/distfiles/php/php-7.3.27/Zend/zend_execute_API.c:756
#13 0x0000000000ac0ce1 in _call_user_function_ex (object=0x0, 
    function_name=0x7fffffff9480, retval_ptr=0x7fffffff9470, param_count=2, 
---Type <return> to continue, or q <return> to quit---
    params=0x7ffff0700440, no_separation=1)
    at /opt/distfiles/php/php-7.3.27/Zend/zend_execute_API.c:598
#14 0x00007fffe63d745e in phalcon_call_user_func_array (retval=0x7fffffff9470, 
    handler=0x7fffffff9480, params=0x7fffffff94d0)
    at /opt/distfiles/php/cphalcon7/ext/kernel/fcall.c:363
#15 0x00007fffe66032ad in phalcon_call_user_func_array_noex (retval=0x7fffffff9470, 
    handler=0x7fffffff9480, params=0x7fffffff94d0)
    at /opt/distfiles/php/cphalcon7/ext/kernel/fcall.h:74
#16 0x00007fffe6608ceb in zim_Phalcon_Dispatcher_dispatch (execute_data=0x7ffff0622150, 
    return_value=0x7fffffffa010) at /opt/distfiles/php/cphalcon7/ext/dispatcher.c:1225
#17 0x0000000000ac1743 in zend_call_function (fci=0x7fffffff9bf0, fci_cache=0x7fffffff9bd0)
    at /opt/distfiles/php/php-7.3.27/Zend/zend_execute_API.c:770
#18 0x00007fffe63d760d in phalcon_call_user_function (fn=0x1b0e110, 
    called_scope=0x1b0a3e0, object=0x7fffffffa020, function_name=0x7fffffff9cc0, 
    retval_ptr=0x7fffffffa010, param_count=0, params=0x0)
    at /opt/distfiles/php/cphalcon7/ext/kernel/fcall.c:432
#19 0x00007fffe63d7d7a in phalcon_call_method_with_params (retval=0x7fffffffa010, 
    object=0x7fffffffa020, ce=0x1b0a3e0, type=phalcon_fcall_method, 
    method_name=0x7fffe673a2a0 "dispatch", method_len=8, param_count=0, 
    params=0x7fffffff9e90) at /opt/distfiles/php/cphalcon7/ext/kernel/fcall.c:531
#20 0x00007fffe6558e72 in zim_Phalcon_Mvc_Application_handle (execute_data=0x7ffff0622100, 
    return_value=0x7ffff06220d0) at /opt/distfiles/php/cphalcon7/ext/mvc/application.c:448
#21 0x0000000000b3d923 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER ()
    at /opt/distfiles/php/php-7.3.27/Zend/zend_vm_execute.h:1106
#22 0x0000000000ba4b4b in execute_ex (ex=0x7ffff0622030)
    at /opt/distfiles/php/php-7.3.27/Zend/zend_vm_execute.h:55527
#23 0x0000000000baa149 in zend_execute (op_array=0x7ffff0605100, return_value=0x0)
    at /opt/distfiles/php/php-7.3.27/Zend/zend_vm_execute.h:60935
---Type <return> to continue, or q <return> to quit---
#24 0x0000000000ad88ba in zend_execute_scripts (type=8, retval=0x0, file_count=3)
    at /opt/distfiles/php/php-7.3.27/Zend/zend.c:1568
#25 0x0000000000a477e5 in php_execute_script (primary_file=0x7fffffffcb60)
    at /opt/distfiles/php/php-7.3.27/main/main.c:2637
#26 0x0000000000bb5abb in php_cli_server_dispatch_script (server=0x15b8180 <server>, 
    client=0x1bebe70) at /opt/distfiles/php/php-7.3.27/sapi/cli/php_cli_server.c:1997
#27 0x0000000000bb6284 in php_cli_server_dispatch (server=0x15b8180 <server>, 
    client=0x1bebe70) at /opt/distfiles/php/php-7.3.27/sapi/cli/php_cli_server.c:2175
#28 0x0000000000bb6aff in php_cli_server_recv_event_read_request (
    server=0x15b8180 <server>, client=0x1bebe70)
    at /opt/distfiles/php/php-7.3.27/sapi/cli/php_cli_server.c:2391
#29 0x0000000000bb6e2b in php_cli_server_do_event_for_each_fd_callback (
    _params=0x7fffffffcdd0, fd=8, event=1)
    at /opt/distfiles/php/php-7.3.27/sapi/cli/php_cli_server.c:2469
#30 0x0000000000bb2f12 in php_cli_server_poller_iter_on_active (
    poller=0x15b8188 <server+8>, opaque=0x7fffffffcdd0, 
    callback=0xbb6c57 <php_cli_server_do_event_for_each_fd_callback>)
    at /opt/distfiles/php/php-7.3.27/sapi/cli/php_cli_server.c:853
#31 0x0000000000bb6ee8 in php_cli_server_do_event_for_each_fd (server=0x15b8180 <server>, 
    rhandler=0xbb69c0 <php_cli_server_recv_event_read_request>, 
    whandler=0xbb6b26 <php_cli_server_send_event>)
    at /opt/distfiles/php/php-7.3.27/sapi/cli/php_cli_server.c:2492
#32 0x0000000000bb6f4d in php_cli_server_do_event_loop (server=0x15b8180 <server>)
    at /opt/distfiles/php/php-7.3.27/sapi/cli/php_cli_server.c:2502
#33 0x0000000000bb7290 in do_cli_server (argc=5, argv=0x15c4100)
    at /opt/distfiles/php/php-7.3.27/sapi/cli/php_cli_server.c:2624
#34 0x0000000000badc72 in main (argc=5, argv=0x15c4100)
    at /opt/distfiles/php/php-7.3.27/sapi/cli/php_cli.c:1399

`

**Comment by yxgong** [comment]
`

        // 可能存在Phalcon与PHP之间的引用计数错误，导致总会出错
        // 只需要这么转换一次，就可以成功操作
        $result = array();
        foreach ($items as $k=>$item){
            $result [$k] = $item;
        }


        //$redis->hMSet($key, $items); // 直接 hMSet就会导致PHP崩溃死掉
        $redis->hMSet($key, $result ); // 如果存储的是经过重新赋值后的数组，就符合预期地运行


`

**Comment by dreamsxin** [comment]
某个数据类型undef得遍历打印看看。

**Comment by dreamsxin** [comment]
已解决
