### ISSUE TITLE
undefined symbol: zend_string_release_ex

### ISSUE THREAD

**Issue by zhouzh1800** [dreamsxin/cphalcon7#516]
PHP Warning:  PHP Startup: Unable to load dynamic library 'phalcon.so' (tried: /usr/lib64/php/modules/phalcon.so (/usr/lib64/php/modules/phalcon.so: undefined symbol: zend_string_release_ex), /usr/lib64/php/modules/phalcon.so.so (/usr/lib64/php/modules/phalcon.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

php版本是
PHP 7.2.34 (cli) (built: Oct  1 2020 13:37:37) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by dreamsxin** [comment]
@zhouzh1800 已修改，不过建议用7.3以上版本。
